services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: nithish
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: studentsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .                       
    image: backend-fastapi
    container_name: backend-fastapi
    depends_on:
      - db                         
    ports:
      - "8000:8000"
    env_file:
      - .env     

  frontend-react:
    build:
      context: ../frontend-react
      args:
        VITE_API_URL: http://localhost:8000
    image: frontend-react
    container_name: frontend-react
    ports:
      - "3000:80"

  frontend-vanillajs:
    build:
      context: ../frontend-vanillaJS
    image: frontend-vanillajs
    container_name: frontend-vanillajs
    ports:
      - "3001:80"
    
volumes:
  pgdata: