"""baseline

Revision ID: da3c792565a0
Revises: 
Create Date: 2026-09-11 10:57:31.448148

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'da3c792565a0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
