"""add phone_number, department, credits, max_capacity

Revision ID: 6ed7a8d0b6c8
Revises: d69c8d3d8392
Create Date: 2026-09-20 00:36:22.883428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ed7a8d0b6c8'
down_revision: Union[str, Sequence[str], None] = 'd69c8d3d8392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('course', sa.Column('credits', sa.Integer(), nullable=False))
    op.add_column('course', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'phone_number')
    op.drop_column('course', 'max_capacity')
    op.drop_column('course', 'credits')
    op.drop_column('course', 'department')
    # ### end Alembic commands ###
