"""add email default and course instructor_name

Revision ID: d69c8d3d8392
Revises: d0e519f18116
Create Date: 2026-09-20 00:24:53.902484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd69c8d3d8392'
down_revision: Union[str, Sequence[str], None] = 'd0e519f18116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'course',
        sa.Column(
            'instructor_name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='Unknown',
        ),
    )
    op.alter_column('course', 'instructor_name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'instructor_name')
    # ### end Alembic commands ###
